feat: Increase tauri runtime threads efficiency
fourviere/fourviere-podcast pull request #58
Opened 2023-11-15 18:31 UTC by newfla

Closes #57 

tokio and tokio-util dependencies have been introduced in order to have async-io in fs, s3 and ftp modules.

2023-11-15 21:07 UTC, brainrepo commented
Simply awesome, I left just a comment about changing the function name in [packages/app/src-tauri/src/commands/fs.rs](https://github.com/fourviere/fourviere-podcast/pull/58/files/90d661a93157eae0d380ba6c6c8a8af36c9eb247#diff-7934beba9d1a48329c9341e44a36605b04e149a1a03f62337304e3c68f77598e)

2023-11-15 21:07 UTC, brainrepo requested changes

2023-11-16 10:49 UTC, newfla commented on packages/app/src-tauri/src/commands/fs.rs
>  pub async fn read_file(path: &str) -> Result<String, String> {
Renamed to read_text_file

2023-11-16 10:54 UTC, newfla commented on packages/app/src-tauri/Cargo.toml
> -suppaftp = { version = "^5.2.2", features = ["native-tls"] }
Caret syntax ^x.y.z should be equivalent to =x.y.z

2023-11-16 11:52 UTC, brainrepo approved these changes
GREAT!!!! Thx @newfla !!!!

2023-11-16 11:52 UTC, merged